name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: corepack enable && yarn init -2 && yarn set version stable && yarn install --mode=<update-lockfile>
      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: corepack enable && yarn init -2 && yarn set version stable && yarn install --mode=<update-lockfile>
      - name: Build Project
        run: yarn build
