name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Corepack with Yarn/Berry
        run: corepack enable && yarn init -2 && yarn set version stable

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --mode=update-lockfile

      - name: Build Project
        run: yarn exec tsc --allowUnreachableCode --noCheck --project ./tsconfig.json

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}